"use client"

import { useParams } from "next/navigation"
import { useQuery } from "@tanstack/react-query"
import { projects, environments } from "@/lib/api"
import { CodeBlock } from "@/components/welcome/code-block"
import { useState } from "react"
import { Plug } from "lucide-react"

export default function IntegrationsPage() {
  const { id: projectId } = useParams<{ id: string }>()
  const { data: project } = useQuery({ queryKey: ["project", projectId], queryFn: () => projects.get(projectId) })
  const { data: envList = [] } = useQuery({ queryKey: ["environments", projectId], queryFn: () => environments.list(projectId) })

  const [selectedEnv, setSelectedEnv] = useState("production")
  const projectName = project?.name ?? "my-service"
  const envName = selectedEnv

  const sections = [
    {
      title: "GitHub Actions",
      description: "Pull secrets into your CI/CD pipeline using a project token stored in GitHub Secrets.",
      blocks: [
        {
          label: "Workflow step",
          prompt: false,
          code: `- name: Pull environment variables
  run: |
    curl -fsSL install.envx.io | sh
    dotkey pull ${envName}
  env:
    ENVX_TOKEN: \${{ secrets.ENVX_TOKEN }}
    ENVX_API_URL: http://localhost:8080
    ENVX_PROJECT: ${projectName}`,
        },
      ],
      note: "Generate a project token under Tokens → it never expires and scoped to this project only.",
    },
    {
      title: "Docker Compose",
      description: "Pull secrets before running containers. The .env file is generated by envx.",
      blocks: [
        {
          label: "Makefile target",
          prompt: false,
          code: `.env:
\tdotkey pull ${envName} --project ${projectName}

dev: .env
\tdocker-compose up`,
        },
        {
          label: "docker-compose.yml",
          prompt: false,
          code: `services:
  app:
    env_file:
      - .env   # generated by: dotkey pull ${envName}`,
        },
      ],
    },
    {
      title: "direnv",
      description: "Auto-load environment variables when you cd into the project directory.",
      blocks: [
        {
          label: ".envrc",
          prompt: false,
          code: `# .envrc — committed to repo, no secrets inside
dotenv_if_exists .env`,
        },
        {
          label: "Generate the .env",
          prompt: true,
          code: `dotkey pull ${envName} --project ${projectName}`,
        },
      ],
      note: "Add .env to .gitignore. Commit .envrc safely — it only loads the file, not the values.",
    },
    {
      title: "Vercel / Railway / Fly.io",
      description: "Import secrets from dotkey into your deployment platform.",
      blocks: [
        {
          label: "Vercel (using vercel CLI)",
          prompt: true,
          code: `dotkey pull ${envName} --project ${projectName} && cat .env | vercel env add`,
        },
        {
          label: "Fly.io",
          prompt: true,
          code: `dotkey pull ${envName} --project ${projectName} && fly secrets import < .env`,
        },
      ],
    },
  ]

  return (
    <div className="p-5 max-w-2xl">
      <div className="flex items-center gap-2 mb-2">
        <Plug className="h-4 w-4 text-muted-foreground" />
        <h1 className="text-sm font-medium">Integrations</h1>
      </div>
      <p className="text-xs text-muted-foreground mb-5">
        Copy-paste snippets for common workflows. Personalized for this project.
      </p>

      {/* env selector */}
      <div className="flex items-center gap-2 mb-6">
        <span className="text-xs text-muted-foreground">Environment:</span>
        <select
          value={selectedEnv}
          onChange={e => setSelectedEnv(e.target.value)}
          className="h-7 text-xs bg-input border border-border rounded px-2 text-foreground"
        >
          {envList.map(e => <option key={e.id} value={e.name}>{e.name}</option>)}
          {envList.length === 0 && <option value="production">production</option>}
        </select>
      </div>

      <div className="space-y-6">
        {sections.map(section => (
          <div key={section.title} className="border border-border rounded-lg overflow-hidden">
            <div className="px-4 py-3 border-b border-border bg-card/50">
              <p className="text-xs font-semibold">{section.title}</p>
              <p className="text-xs text-muted-foreground mt-0.5">{section.description}</p>
            </div>
            <div className="p-4 space-y-3">
              {section.blocks.map(block => (
                <div key={block.label}>
                  <p className="text-xs text-muted-foreground mb-1.5">{block.label}</p>
                  <CodeBlock code={block.code} prompt={block.prompt} />
                </div>
              ))}
              {section.note && (
                <p className="text-xs text-muted-foreground mt-2 pt-2 border-t border-border">
                  💡 {section.note}
                </p>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
